services:
    core.log_request_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle:LogRequest']

    core.emotion_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle:Emotion']

    core.theme_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle:Theme']

    core.remark_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle:Remark']

    core.response_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle:Response']

    core.vote_response_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle:VoteResponse']

    core.vote_remark_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle:VoteRemark']

    core.report_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle:Report']

    core.news_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle:News']

    core.grade_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle:Grade']

    core.action_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['CoreBundle:Action']
