log_request:
    type: rest
    resource: CoreBundle\Controller\LogRequestController

emotion:
    type: rest
    resource: CoreBundle\Controller\EmotionController

theme:
    type: rest
    resource: CoreBundle\Controller\ThemeController

remark:
    type: rest
    resource: CoreBundle\Controller\RemarkController
