services:
    core.base_voter:
        class: CoreBundle\Security\AbstractVoter
        abstract: true
        arguments: ['@security.access.decision_manager']
        public: false
#        tags:
#            - { name: security.voter }

    core.emotion_voter:
        class: CoreBundle\Security\EmotionVoter
        parent: core.base_voter
        tags:
            - { name: security.voter }

    core.theme_voter:
        class: CoreBundle\Security\ThemeVoter
        parent: core.base_voter
        tags:
            - { name: security.voter }
