<?php

namespace LKE\RemarkBundle\Repository;

use Doctrine\ORM\EntityRepository;
use LKE\RemarkBundle\Entity\Remark;

/**
 * RemarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemarkRepository extends EntityRepository
{
    public function getPostedRemark($limit, $page)
    {
        $qb = $this->queryPostedRemark()
            ->setMaxResults($limit)
            ->setFirstResult($page * $limit);

        return $qb->getQuery()->getResult();
    }

    public function queryPostedRemark()
    {
        $qb = $this->createQueryBuilder('r')
            ->leftJoin('r.theme', 't')
            ->leftJoin('r.emotion', 'e')
            ->leftJoin('r.responses', 're')
            ->addSelect('t')
            ->addSelect('e')
            ->addSelect('re')
            ->where('r.postedAt is not null')
            ->orderBy('r.postedAt', 'DESC');

        return $qb;
    }

    public function getUnpublishedRemark($limit, $page)
    {
        $qb = $this->queryUnpublishedRemark()
            ->setMaxResults($limit)
            ->setFirstResult($page * $limit);

        return $qb->getQuery()->getResult();
    }

    public function queryUnpublishedRemark()
    {
        $qb = $this->createQueryBuilder('r')
            ->where('r.postedAt is null');

        return $qb;
    }

    public function getCompleteRemark($id)
    {
        $qb = $this->createQueryBuilder('r')
                ->leftJoin('r.theme', 't')
                ->leftJoin('r.emotion', 'e')
                ->addSelect('t')
                ->addSelect('e')
                ->where('r.id = :id')
                ->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function userHasVote(Remark $remark, $user, $type)
    {
        $qb = $this->createQueryBuilder('r')
            ->select('COUNT(r.id)')
            ->join('r.votes', 'v')
            ->where('r = :remark')
            ->andWhere('v.user = :user')
            ->andWhere('v.type = :type')
            ->setParameters(array(
                "remark" => $remark,
                "user" => $user,
                "type" => $type
            ));

        return (bool) $qb->getQuery()->getSingleScalarResult();
    }

    public function countPublishedRemark()
    {
        $qb = $this->createQueryBuilder("r")
                ->select("COUNT(r.id)")
                ->where("r.postedAt is not null");

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function countUnpublishedRemark()
    {
        $qb = $this->createQueryBuilder("r")
            ->select("COUNT(r.id)")
            ->where("r.postedAt is null");

        return $qb->getQuery()->getSingleScalarResult();
    }
}
