<?php

namespace LKE\RemarkBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function queryReportedResponses()
    {
        $qb = $this->createQueryBuilder('r')
                    ->select('COUNT(r.response) AS count_report', 're.sentence', 're.id AS id_response')
                    ->leftJoin('r.response', 're')
                    ->groupBy('r.response')
                    ->orderBy('count_report', 'DESC');

        return $qb->getQuery();
    }

    public function getReportedResponses()
    {
        $query = $this->queryReportedResponses();

        return $query->getArrayResult();
    }
}
