imports:
    - { resource: config_dev.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_test.yml"
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    templating:
        engines: ['twig']

web_profiler:
    toolbar: false

monolog:
    handlers:
        main:
            type:           fingers_crossed
            action_level:   error
            handler:        grouped
        grouped:
            type:           group
            members:        [streamed, swift]
        streamed:
            type:           stream
            path:           "%kernel.logs_dir%/%kernel.environment%.log"
            level:          debug
        swift:
            type:           swift_mailer
            excluded_404s:  ["^/"]
            from_email:     "%mail_sender%"
            to_email:       "%mail_developer%"
            subject:        "[TESTING] [365raiponce]"
            level:          debug
