imports:
    - { resource: config.yml }

nelmio_api_doc:
    cache:
        enabled: true

doctrine:
    orm:
        metadata_cache_driver: redis
        query_cache_driver: redis
#        result_cache_driver: redis

monolog:
    handlers:
        main:
            type:           fingers_crossed
            action_level:   error
            handler:        grouped
        grouped:
            type:           group
            members:        [streamed, swift]
        streamed:
            type:           stream
            path:           "%kernel.logs_dir%/%kernel.environment%.log"
            level:          debug
        swift:
            type:           swift_mailer
            from_email:     "%mail_sender%"
            to_email:       "%mail_admin%"
            subject:        "[ERROR] %app_name%"
            level:          debug

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://%redis_host%:%redis_port%/%redis_index%
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default
        query_cache:
            client: default
            entity_manager: default
#        result_cache:
#            client: default
#            entity_manager: default
