imports:
    - { resource: config.yml }

nelmio_api_doc:
    cache:
        enabled: true

doctrine:
    orm:
        metadata_cache_driver: redis
        query_cache_driver: redis
        result_cache_driver: redis

monolog:
    handlers:
        main_error:
            type:           fingers_crossed
            action_level:   error
            handler:        streamed
            excluded_404s:
                - ^/
        streamed:
            type:           rotating_file
            max_files:      30
            path:           "%kernel.logs_dir%/%kernel.environment%.log"
            level:          debug

        main_critical:
            type:           fingers_crossed
            action_level:   critical
            handler:        slack
        slack:
            type:           slack
            token:          "%env(SLACK_TOKEN)%"
            channel:        "%env(SLACK_CHANNEL)%"
            level:          warning

        auth:
            type:           rotating_file
            max_files:      30
            path:           "%kernel.logs_dir%/%kernel.environment%-auth.log"
            level:          warning
            channels:       security

        doctrine:
            type:           rotating_file
            max_files:      30
            path:           "%kernel.logs_dir%/%kernel.environment%-doctrine.log"
            level:          warning
            channels:       doctrine

snc_redis:
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default
        query_cache:
            client: default
            entity_manager: default
        result_cache:
            client: default
            entity_manager: default
