imports:
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@CoreBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%env(SECRET)%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%env(DATABASE_HOST)%"
        port:     "%env(DATABASE_PORT)%"
        dbname:   "%env(DATABASE_NAME)%"
        user:     "%env(DATABASE_USER)%"
        password: "%env(DATABASE_PASSWORD)%"
        charset:  UTF8
        server_version: 5.7
        # https://coderwall.com/p/goyc8w/how-to-stop-doctrine-from-turning-integer-into-string
        options:
            20: false
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                DAY: DoctrineExtensions\Query\Mysql\Day
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year

# Swiftmailer Configuration
swiftmailer:
    transport: "%env(MAILER_TRANSPORT)%"
    host:      "%env(MAILER_HOST)%"
    username:  "%env(MAILER_USER)%"
    password:  "%env(MAILER_PASSWORD)%"
    port:      "%env(MAILER_PORT)%"
    encryption: "ssl"
    sender_address: "%env(MAIL_SENDER)%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address:     "%env(MAIL_SENDER)%"
        sender_name: "%env(APP_NAME)%"
    service:
        mailer: user.mailer

fos_rest:
    view:
        formats:
            json: true
        view_response_listener: true
    routing_loader:
        default_format: json
        include_format: false
    serializer:
        serialize_null: true
    versioning:
        enabled: true
        resolvers:
            query: false
            custom_header:
                enabled: true
                header_name: "X-Accept-Version"
            media_type: false

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/config/serializer/fos"

fos_oauth_server:
    db_driver: orm
    client_class:        UserBundle\Entity\Client
    access_token_class:  UserBundle\Entity\AccessToken
    refresh_token_class: UserBundle\Entity\RefreshToken
    auth_code_class:     UserBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username_email

# http://symfony.com/doc/current/bundles/NelmioApiDocBundle/configuration-reference.html
nelmio_api_doc:
    cache:
        file: '%kernel.cache_dir%/api-doc-%kernel.environment%.cache'

nelmio_cors:
    defaults:
        allow_origin:   ["%env(CORS_ALLOW_ORIGIN)%"]
        allow_methods:  ["POST", "PUT", "PATCH", "GET", "DELETE", "OPTIONS"]
        allow_headers:  ["Content-Type", "Authorization", "X-Accept-Version"]
        expose_headers: ["link"]
        max_age:        3600
    paths:
        '^/': ~

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/%env(REDIS_INDEX)%"
