imports:
    - { resource: config.yml }

nelmio_api_doc:
    cache:
        enabled: true

doctrine:
    orm:
        metadata_cache_driver: redis
        query_cache_driver: redis
        result_cache_driver: redis

monolog:
    handlers:
        main:
            type:           fingers_crossed
            action_level:   error
            handler:        grouped
            excluded_404s:
                - ^/
        grouped:
            type:           group
            members:        [streamed, slack]
        streamed:
            type:           rotating_file
            max_files:      30
            path:           "%kernel.logs_dir%/%kernel.environment%.log"
            level:          debug
        slack:
            type:           slack
            token:          "%slack_token%"
            channel:        "%slack_channel%"
            level:          warning

        auth:
            type:           rotating_file
            max_files:      30
            path:           "%kernel.logs_dir%/%kernel.environment%-auth.log"
            level:          warning
            channels:       security

        doctrine:
            type:           rotating_file
            max_files:      30
            path:           "%kernel.logs_dir%/%kernel.environment%-doctrine.log"
            level:          warning
            channels:       doctrine

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://%redis_host%:%redis_port%/%redis_index%
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default
        query_cache:
            client: default
            entity_manager: default
        result_cache:
            client: default
            entity_manager: default
