api:
    type: rest
    resource: "routing_rest.yml"
    prefix: /api

api_login_check:
   path: /api/login_check

api_preflight:
    path: /preflight
    defaults: { _controller: LKECoreBundle:Cors:preflight }
