api_lke_user:
    type:     rest
    resource: "@LKEUserBundle/Resources/config/routing.yml"
    name_prefix: api_

api_lke_remark:
    type:     rest
    resource: "@LKERemarkBundle/Resources/config/routing.yml"
    name_prefix: api_

api_lke_admin:
    type:     rest
    resource: "@LKEAdminBundle/Resources/config/routing.yml"
    name_prefix: api_admin_
    prefix: admin/
