api_lke_user:
    type:     rest
    resource: "@LKEUserBundle/Resources/config/routing.yml"
    name_prefix: api_

api_lke_remark:
    type:     rest
    resource: "@LKERemarkBundle/Resources/config/routing.yml"
    name_prefix: api_

