<?php

namespace LKE\RemarkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmotionRepository extends EntityRepository
{
    public function getEmotions($limit, $page)
    {
        $qb = $this->createQueryBuilder('e')
                ->setFirstResult($page * $limit)
                ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
