<?php

namespace LKE\RemarkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseRepository extends EntityRepository
{
    public function getResponsesByRemark($idRemark, $idUser, $limit, $page)
    {
        $qb = $this->createQueryBuilder('r')
            ->where('r.remark = :idRemark')
            ->andWhere('r.postedAt is not null OR r.author = :idAuthor')
            ->setParameter('idRemark', $idRemark)
            ->setParameter('idAuthor', $idUser)
            ->setFirstResult($page * $limit)
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    public function getMyResponses($idUser, $limit, $page)
    {
        $qb = $this->createQueryBuilder('r')
            ->andWhere('r.author = :idAuthor')
            ->setParameter('idAuthor', $idUser)
            ->setFirstResult($page * $limit)
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
