<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Action;
use CoreBundle\Service\KeyBuilder;
use Doctrine\ORM\QueryBuilder;
use UserBundle\Entity\User;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends AbstractDateRepository
{
    /**
     * @var int
     */
    private $lifetimeCacheScore;


    /**
     * @param int $lifetime
     */
    public function setLifetimeCacheScore(int $lifetime)
    {
        $this->lifetimeCacheScore = $lifetime;
    }

    /**
     * @return QueryBuilder
     */
    public function sumScore() : QueryBuilder
    {
        $qb = $this->createQueryBuilder('h');

        $this->safeLeftJoin($qb, 'action', 'a');

        $qb->select('SUM(a.point) AS nb');

        return $qb;
    }

    /**
     * @return QueryBuilder
     */
    public function qbFindAll() : QueryBuilder
    {
        return $this->createQueryBuilder('h');
    }

    /**
     * @param User $user
     *
     * @return QueryBuilder
     */
    public function qbFindAllByUser(User $user) : QueryBuilder
    {
        $qb = $this->qbFindAll();

        $qb
            ->andWhere($qb->expr()->eq('h.user', ':user'))
            ->setParameter('user', $user)
        ;

        return $qb;
    }

    /**
     * @param Action    $action
     * @param User      $user
     * @param \DateTime $day
     *
     * @return int
     */
    public function countActionForUserAndDay(Action $action, User $user, \DateTime $day) : int
    {
        $qb = $this->createQueryBuilder('h');
        $expr = $qb->expr();

        $today    = $day->modify('today');
        $tomorrow = $today->modify('tomorrow');

        $qb
            ->select($expr->count('h.id'))
            ->where(
                $expr->eq('h.action', ':action'),
                $expr->eq('h.user', ':user'),
                $expr->gte('h.createdAt', ':today'),
                $expr->lt('h.createdAt', ':tomorrow')
            )
            ->setParameters([
                'action'    => $action,
                'user'      => $user,
                'today'     => $today,
                'tomorrow'  => $tomorrow,
            ])
        ;

        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * @param User $user
     *
     * @return int
     */
    public function countScoreForUser(User $user) : int
    {
        $qb = $this->createQueryBuilder('h');

        $qb
            ->select('SUM(a.point)')
            ->leftJoin('h.action', 'a')
            ->where(
                $qb->expr()->eq('h.usedForScore', true),
                $qb->expr()->eq('h.user', ':user')
            )
            ->setParameter('user', $user)
        ;

        $query = $qb->getQuery();

        $query
            ->useResultCache(true, $this->lifetimeCacheScore, KeyBuilder::keyScoreUser($user))
        ;

        return $query->getSingleScalarResult() ?? 0;
    }

    /**
     * @param QueryBuilder $qb
     * @param int|string   $isUsed
     *
     * @return QueryBuilder
     */
    public function filterByIsUsedForScore(QueryBuilder $qb, $isUsed) : QueryBuilder
    {
        $alias = $this->getAlias($qb);

        $qb
            ->andWhere($alias . 'usedForScore = :used_for_score')
            ->setParameter('used_for_score', (bool) $isUsed)
        ;

        return $qb;
    }

    /**
     * @param QueryBuilder $qb
     * @param string|array $value
     *
     * @return QueryBuilder
     */
    public function filterByAction(QueryBuilder $qb, $value) : QueryBuilder
    {
        $alias = $this->getAlias($qb);

        return $this->getEqOrIn($qb, $value, $alias . 'action', 'action');
    }

    /**
     * @param QueryBuilder $qb
     * @param string|array $value
     *
     * @return QueryBuilder
     */
    public function filterByUser(QueryBuilder $qb, $value) : QueryBuilder
    {
        $alias = $this->getAlias($qb);

        return $this->getEqOrIn($qb, $value, $alias . 'user', 'user');
    }

    /**
     * @param QueryBuilder $qb
     * @param string       $orderBy
     * @param string       $order
     *
     * @return QueryBuilder
     */
    public function orderByIsUsedForScore(QueryBuilder $qb, string $orderBy, string $order) : QueryBuilder
    {
        return $this->applyOrder($qb, 'usedForScore', $order);
    }

    /**
     * @param QueryBuilder $qb
     * @param string       $orderBy
     * @param string       $order
     *
     * @return QueryBuilder
     */
    public function orderByUser(QueryBuilder $qb, string $orderBy, string $order) : QueryBuilder
    {
        $alias = 'u';

        $this->safeLeftJoin($qb, 'user', $alias);

        return $this->applyOrder($qb, '.username', $order, $alias);
    }

    /**
     * @param QueryBuilder $qb
     * @param string       $groupBy
     *
     * @return QueryBuilder
     */
    public function groupByUser(QueryBuilder $qb, string $groupBy) : QueryBuilder
    {
        $this->safeLeftJoin($qb, 'user', 'u');

        return $this->groupBy($qb, 'u.id', 'user_id');
    }

    /**
     * @param QueryBuilder $qb
     * @param string       $groupBy
     *
     * @return QueryBuilder
     */
    public function groupByAction(QueryBuilder $qb, string $groupBy) : QueryBuilder
    {
        $this->safeLeftJoin($qb, 'action', 'a');

        return $this->groupBy($qb, 'a.id', 'action_id');
    }

    /**
     * @param QueryBuilder $qb
     * @param string       $groupBy
     *
     * @return QueryBuilder
     */
    public function groupByIsUsedForScore(QueryBuilder $qb, string $groupBy) : QueryBuilder
    {
        $alias = $this->getAlias($qb);

        return $this->groupBy($qb, $alias . 'usedForScore', 'is_used_for_score');
    }
}
