<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Action;
use UserBundle\Entity\User;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends AbstractRepository
{
    /**
     * @param Action $action
     * @param User   $user
     *
     * @return int
     */
    public function countActionTodayForUser(Action $action, User $user) : int
    {
        $qb = $this->createQueryBuilder('h');
        $expr = $qb->expr();

        $today = strtotime('today');

        $qb
            ->select($expr->count('h.id'))
            ->where(
                $expr->eq('h.action', ':action'),
                $expr->eq('h.user', ':user'),
                $expr->gte('h.createdAt', ':today')
            )
            ->setParameters([
                'action' => $action,
                'user' => $user,
                'today' => $today
            ])
        ;

        return $qb->getQuery()->getSingleScalarResult();
    }
}
