<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends AbstractRepository
{
    /**
     * @return QueryBuilder
     */
    public function qbFindAll() : QueryBuilder
    {
        return $this->createQueryBuilder('e');
    }

    /**
     * @param QueryBuilder $qb
     * @param string|array $name
     *
     * @return QueryBuilder
     */
    public function filterByName(QueryBuilder $qb, $name) : QueryBuilder
    {
        return $this->filterBy($qb, 'name', $name);
    }
}
