<?php

namespace CoreBundle\Repository;

/**
 * VoteRemarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRemarkRepository extends AbstractDateRepository
{

}
