remark:
    type:     rest
    resource: LKE\RemarkBundle\Controller\RemarkController

theme:
    type:     rest
    resource: LKE\RemarkBundle\Controller\ThemeController

emotion:
    type:     rest
    resource: LKE\RemarkBundle\Controller\EmotionController
