services:
    lke_remark.get_remark:
        class: LKE\RemarkBundle\Service\GetRemark
        arguments: [@doctrine, @lke_user.access]

    lke_remark.get_response:
        class: LKE\RemarkBundle\Service\GetResponse
        arguments: [@doctrine, @lke_user.access]

    lke_remark.get_theme:
        class: LKE\RemarkBundle\Service\GetTheme
        arguments: [@doctrine]

    lke_remark.get_emotion:
        class: LKE\RemarkBundle\Service\GetEmotion
        arguments: [@doctrine]
