services:
    lke_remark.remark_voter:
        class: LKE\RemarkBundle\Security\RemarkVoter
        parent: lke_core.base_voter
        tags:
            - { name: security.voter }

    lke_remark.emotion_voter:
        class: LKE\RemarkBundle\Security\EmotionVoter
        parent: lke_core.base_voter
        tags:
            - { name: security.voter }

    lke_remark.theme_voter:
        class: LKE\RemarkBundle\Security\ThemeVoter
        parent: lke_core.base_voter
        tags:
            - { name: security.voter }

    lke_remark.response_voter:
        class: LKE\RemarkBundle\Security\ResponseVoter
        parent: lke_core.base_voter
        tags:
            - { name: security.voter }
