services:
    lke_core.paginator:
        class: LKE\CoreBundle\Service\Paginator

    lke_core.get_entity:
        class: LKE\CoreBundle\Service\GetEntity
        arguments: ['@doctrine', '@security.authorization_checker']

    lke_core.parse_csv:
        class: LKE\CoreBundle\Service\ParseCSV

    lke_core.base_voter:
        class: LKE\CoreBundle\Security\Voter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
