CoreBundle\Entity\Remark:
    exclusion_policy: ALL

    properties:
        id:
            expose: true
        context:
            expose: true
        sentence:
            expose: true
        postedAt:
            expose: true
        createdAt:
            expose: true
            groups: [my, admin]
        updatedAt:
            expose: true
            groups: [admin]
        scaleEmotion:
            expose: true
        email:
            expose: true
            groups: [admin]

    relations:
       # links
        -
            rel: self
            href:
                route: api_get_remark
                parameters:
                    remark_id: expr(object.getId())

        # embedded
        -
            rel: count_published_responses
            embedded:
                content: expr(object.countPublishedResponses())
            exclusion:
                groups: [stats]

        -
            rel: count_unpublished_responses
            embedded:
                content: expr(object.countUnpublishedResponses())
            exclusion:
                groups: [stats, admin]

        -
            rel: count_vote_is_sexist
            embedded:
                content: expr(object.getCountVoteIsSexist())
            exclusion:
                groups: [stats]

        -
            rel: count_vote_already_lived
            embedded:
                content: expr(object.getCountVoteAlreadyLive())
            exclusion:
                groups: [stats]

        -
            rel: theme
            embedded:
                content: expr(object.getTheme())

        -
            rel: emotion
            embedded:
                content: expr(object.getEmotion())


# TODO user has vote for ...