CoreBundle\Entity\Action:
    exclusion_policy: ALL

    properties:
        id:
            expose: true
        point:
            expose: true
        limitPerDay:
            expose: true
        description:
            expose: true

    relations:
        -
            rel: self
            href:
                route: api_get_action
                parameters:
                    action_id: expr(object.getId())
