CoreBundle\Entity\History\HistoryResponsePublished:
    exclusion_policy: ALL

    relations:
        # embedded
        -
            rel: response
            embedded:
                content: expr(object.getResponse())
