<?php

namespace LKE\VoteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRemarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRemarkRepository extends EntityRepository
{
}
