<?php

namespace LKE\VoteBundle\Repository;

/**
 * VoteResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteResponseRepository extends VoteRepository
{
    public function getVoteByUserAndResponse($response, $user)
    {
        $qb = $this->createQueryBuilder('v')
            ->where("v.response = :response")
            ->andWhere("v.user = :user")
            ->setParameters(array(
                "response" => $response,
                "user" => $user
            ));

        return $qb->getQuery()->getOneOrNullResult();
    }
}
