<?php

namespace LKE\VoteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
    public function countVoteForUser($user)
    {
        $date = new \DateTime("now -24hours");

        $qb = $this->createQueryBuilder('v')
                ->select("COUNT(v.id)")
                ->where('v.user = :user')
                ->andWhere('v.createAt > :date')
                ->setParameters(array(
                    'user' => $user,
                    'date' => $date
                ));

        return $qb->getQuery()->getSingleScalarResult();
    }
}
