<?php

namespace LKE\VoteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRemarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRemarkRepository extends EntityRepository
{
    public function getVoteByUserAndRemark($remark, $user, $type)
    {
        $qb = $this->createQueryBuilder('v')
            ->where("v.remark = :remark")
            ->andWhere("v.type =: type")
            ->andWhere("v.user = :user")
            ->setParameters(array(
                "remark" => $remark,
                "type" => $type,
                "user" => $user
            ));

        return $qb->getQuery()->getSingleResult();
    }
}
