admin_remark:
    type:     rest
    resource: LKE\AdminBundle\Controller\RemarkController

admin_theme:
    type:     rest
    resource: LKE\AdminBundle\Controller\ThemeController

admin_emotion:
    type:     rest
    resource: LKE\AdminBundle\Controller\EmotionController

admin_response:
    type:     rest
    resource: LKE\AdminBundle\Controller\ResponseController

admin_user:
    type:     rest
    resource: LKE\AdminBundle\Controller\UserController
