<?php

namespace LKE\VoteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
    public function getVoteByUserAndResponse($response, $user)
    {
        $qb = $this->createQueryBuilder('v')
                    ->where("v.response = :response")
                    ->andWhere("v.user = :user")
                    ->setParameters(array(
                        "response" => $response,
                        "user" => $user
                    ));

        return $qb->getQuery()->getSingleResult();
    }

    public function countVoteForUser($user)
    {
        $date = new \DateTime("now -24hours");

        $qb = $this->createQueryBuilder('v')
                ->select("COUNT(v.id)")
                ->where('v.user = :user')
                ->andWhere('v.createAt > :date')
                ->setParameters(array(
                    'user' => $user,
                    'date' => $date
                ));

        return $qb->getQuery()->getSingleScalarResult();
    }
}
